name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: rustup update

    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: |
        cargo test --verbose --all-features --workspace && \
        cargo install cargo-tarpaulin && \
        cargo tarpaulin --verbose --all-features --workspace --out Xml

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml

    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@v2
